apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: k8s-nfs
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  archiveOnDelete: "true"
