apiVersion: v1
kind: Namespace
metadata:
  name: minio

---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  creationTimestamp: null
  name: minio
  namespace: minio
scheduler:
  name: ""
spec:
  certConfig: {}
  console:
    consoleSecret:
      name: minio-console-secret
    image: minio/console:v0.7.5
    replicas: 2
    resources: {}
  credsSecret:
    name: minio-creds-secret
  image: minio/minio:RELEASE.2021-06-17T00-10-46Z
  imagePullSecret: {}
  mountPath: /export
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - minio
          topologyKey: kubernetes.io/hostname
    resources: {}
    servers: 1
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 12800Mi
        storageClassName: k8s-nfs
      status: {}
    volumesPerServer: 4
  requestAutoCert: true
status:
  availableReplicas: 0
  certificates: {}
  currentState: ""
  pools: null
  revision: 0
  syncVersion: ""

---
apiVersion: v1
data:
  accesskey: bWluaW8=
  secretkey: bWluaW8xMjM=
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-creds-secret
  namespace: minio

---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: YWRtaW4=
  CONSOLE_PBKDF_PASSPHRASE: OTBkYWE4N2QtYTBkMC00OWI4LWE5NTgtZTQzYmJkYzVlZDNh
  CONSOLE_PBKDF_SALT: MDRjYmZiNmItODllMS00MjM5LWE1ODAtZTliNzExMWM2NGZk
  CONSOLE_SECRET_KEY: MmQzMzQyMmMtOWVkZS00NTUxLTk1YTItZWIzMzljZWNmMTY1
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-console-secret
  namespace: minio

